[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ECT SQI"
authors = [{name = "Kayser", email = "max.kayser@uni-bonn.de"}]
dynamic = ["version", "description"]
